[docs] Divider docs + demos
svelteuidev/svelteui pull request #81
Opened 2022-05-28 14:59 UTC by BeeMargarida

* Divider demos
* Divider docs
* Added missing vertical margin to divider
* Added `px` to stitches spacing
* Removed unused code from center docs

### Before submitting the PR, please make sure you do the following

- [X] Read the [Contributing guide](https://github.com/svelteuidev/svelteui/blob/main/CONTRIBUTING.md)
- [X] Prefix your PR title with `[@svelteui/core]`, `[@svelteui/actions]`, `[@svelteui/motion]`, `[@svelteui/core]`, `[core]`, or `[docs]`.
- [X] This message body should clearly illustrate what problems it solves.

### Tests

- [X] Run the tests with `npm test` and lint the project with `npm run lint` or just run `npm run repo:prepush` and check to see if it's passing.

2022-05-28 15:02 UTC, BeeMargarida commented
Ci failing due to actions package tests, which is fixed in the other PR

2022-05-28 22:19 UTC, Brisklemonade requested changes

2022-05-28 22:19 UTC, Brisklemonade commented on packages/svelteui-core/src/lib/stitches.config.ts
> +				xl: '24px',
This should be a number value and not a string value.

2022-05-29 19:27 UTC, Brisklemonade approved these changes

2022-05-29 19:28 UTC, merged